import { Cable, Network, Zap, Server, LayoutGrid, Wifi, Camera, ArrowRightLeft, DatabaseZap } from "lucide-react";

export const SERVICES = [
  {
    slug: "structured-cabling",
    icon: Cable,
    title: "Structured Cabling Installs",
    tagline: "Complete commercial structured cabling systems built for reliability and scale.",
    desc: "Complete commercial structured cabling systems for new construction, tenant improvements, and building expansions. We handle everything from pathway planning to cable pulling, termination, and testing. Our installations follow TIA/EIA standards to ensure a system that performs today and scales with your business tomorrow.",
    longDesc: "Whether you're building out a new office from scratch or upgrading aging infrastructure in an existing facility, Iowa Structure Cabling Solution provides end-to-end structured cabling services. Our team handles the full project lifecycle — from initial site survey and pathway planning through final cable testing and documentation. Every installation is completed with commercial-grade materials, organized runs, and clearly labeled terminations.",
    includes: ["Cable pathway planning", "J-hook and cable tray installation", "Horizontal and backbone cabling", "Termination and testing", "Labeling and documentation"],
    ideal: "New construction, office buildouts, commercial renovations, and multi-floor installations.",
    benefits: ["Organized, scalable infrastructure", "Reduced network downtime", "Clean, professional appearance", "Industry-standard compliance"],
    caseStudy: {
      title: "15,000 sq ft Office Buildout — Des Moines, IA",
      summary: "A growing insurance firm contracted us to cable their new five-floor office space before move-in. We installed over 400 CAT6A drops, three network closets, and complete fiber backbone — all completed two weeks ahead of schedule with zero failed drops on final certification.",
      result: "400+ drops | 3 closets | On-time delivery",
    },
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    ],
  },
  {
    slug: "cat6-drops",
    icon: Network,
    title: "CAT6 / CAT6A Cable Drops",
    tagline: "High-performance copper cable drops for every workstation, device, and access point.",
    desc: "High-performance copper cable drops for workstations, VoIP phones, printers, access points, and security devices. Every drop is terminated, tested, and labeled.",
    longDesc: "CAT6 and CAT6A drops are the backbone of any modern office network. Our technicians run clean, organized cable runs through walls, ceilings, and conduit — then terminate, test, and label every single drop. We handle single drops, bulk office installations, and everything in between. CAT6A supports 10Gbps speeds at up to 100 meters, making it the smart choice for future-proofing your network.",
    includes: ["CAT6 and CAT6A cable runs", "Keystone jack termination", "Wall plate installation", "Cable testing and certification", "Drop labeling and mapping"],
    ideal: "Office expansions, additional workstations, conference rooms, and device connectivity needs.",
    benefits: ["10Gbps capable (CAT6A)", "Future-proof connectivity", "Tested and certified performance", "Neat, organized runs"],
    caseStudy: {
      title: "Office Expansion — Cedar Rapids, IA",
      summary: "A regional accounting firm needed 60 additional drops across two floors of an existing building. We completed the work over a single weekend to avoid disruption, running cable through existing pathways and terminating at two patch panels — all tested and certified by Monday morning.",
      result: "60 drops | Weekend installation | Zero downtime",
    },
    gallery: [
      "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    ],
  },
  {
    slug: "fiber-optic",
    icon: Zap,
    title: "Fiber Optic Runs & Terminations",
    tagline: "Ultra-high bandwidth fiber installations for backbone, campus, and data center connectivity.",
    desc: "Single-mode and multi-mode fiber optic installations for backbone connectivity, inter-building links, and high-speed data transmission needs.",
    longDesc: "Fiber optic cabling delivers the highest bandwidth over the longest distances — making it essential for campus backbones, inter-building links, and data center feeds. Iowa Structure Cabling Solution installs both single-mode and multi-mode fiber, performs fusion splicing, and provides OTDR testing documentation so you know your fiber is performing at spec. We also mount splice trays, fiber enclosures, and patch panels to keep everything organized.",
    includes: ["Fiber pathway installation", "Single-mode and multi-mode runs", "Fusion splicing and termination", "Fiber testing and OTDR results", "Splice tray and enclosure mounting"],
    ideal: "Multi-building campuses, data center connections, ISP handoffs, and long-distance backbone links.",
    benefits: ["Ultra-high bandwidth capacity", "Long-distance reliability", "Future-proof infrastructure", "Low signal loss"],
    caseStudy: {
      title: "Campus Fiber Backbone — Iowa City, IA",
      summary: "A medical services campus needed inter-building fiber connecting four buildings across a parking lot. We trenched and installed conduit, ran 12-strand single-mode fiber, and performed fusion splicing and OTDR testing on all connections — delivering sub-0.1dB loss on every span.",
      result: "4 buildings connected | 12-strand SMF | OTDR certified",
    },
    gallery: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    ],
  },
  {
    slug: "patch-panels-rack-cleanup",
    icon: Server,
    title: "Patch Panels & Rack Cleanup",
    tagline: "Transform a tangled mess into a clean, organized, and fully documented network rack.",
    desc: "Bring order to your network infrastructure with professional patch panel installation, rack organization, and cable management solutions.",
    longDesc: "A disorganized network rack isn't just an eyesore — it slows down troubleshooting, blocks airflow, and creates risk during moves and changes. Our rack cleanup service includes new patch panel installation, complete cable re-dressing, velcro tie organization, and full port labeling and documentation. The result is a rack your team can actually work with.",
    includes: ["Patch panel installation and termination", "Rack-mount hardware installation", "Cable management and dressing", "Labeling and port mapping", "Velcro and cable management accessories"],
    ideal: "Existing racks needing reorganization, new rack installs, server room upgrades, and network closets.",
    benefits: ["Easier troubleshooting", "Improved airflow", "Professional appearance", "Faster moves and changes"],
    caseStudy: {
      title: "Network Room Cleanup — Ames, IA",
      summary: "A manufacturing facility's network room had grown unmanaged for years — cables zip-tied in bundles with no labels and equipment shoved wherever it fit. We spent two days completely reorganizing the rack, re-terminating all patch panels, installing cable management, and delivering a full port map. The IT manager said it cut their average troubleshooting time in half.",
      result: "Full rack rebuild | Port-mapped | 50% faster troubleshooting",
    },
    gallery: [
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80",
    ],
  },
  {
    slug: "network-closet-buildout",
    icon: LayoutGrid,
    title: "Network Closet Buildout",
    tagline: "Turn-key network closet design and installation — your hub, built right from day one.",
    desc: "Full turn-key network closet design and buildout, including rack mounting, power, cable management, and equipment organization for a reliable hub.",
    longDesc: "The network closet is the heart of your building's IT infrastructure. We design and build fully functional network closets from scratch — wall-mount or floor-mount racks, patch panels, switches, power strips, UPS units, cable pathways, and everything in between. All work is completed to industry standards with proper ventilation considerations and full labeling and documentation.",
    includes: ["Wall-mount or floor-mount rack installation", "Patch panel and switch mounting", "Power strip and UPS placement", "Cable pathway into closet", "Labeling, testing, and documentation"],
    ideal: "New offices, tenant spaces, warehouses, schools, and any commercial space needing a dedicated network closet.",
    benefits: ["Centralized network management", "Clean, organized hub", "Easy expansion and maintenance", "Cooled and ventilated setup"],
    caseStudy: {
      title: "New Tenant Office — Davenport, IA",
      summary: "A law firm moving into a new tenant space needed a complete network closet built before their IT equipment arrived. We installed a 12U wall-mount rack, 2 patch panels, a power strip, and all cabling pathways — then coordinated with their IT team for seamless equipment installation the following day.",
      result: "12U rack build | 2-day turnaround | Move-in ready",
    },
    gallery: [
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    ],
  },
  {
    slug: "wifi-access-point",
    icon: Wifi,
    title: "Wi-Fi Access Point Installation",
    tagline: "Commercial Wi-Fi AP cabling and mounting for reliable coverage throughout your facility.",
    desc: "Commercial-grade Wi-Fi access point mounting, cabling, and deployment for reliable wireless coverage throughout your facility.",
    longDesc: "Strong wireless coverage starts with proper cabling. We survey your facility, plan optimal AP locations for full coverage, run CAT6 drops to each location, and mount APs cleanly on ceiling or wall. We coordinate with your IT team or MSP for configuration and can work around your business hours to minimize disruption.",
    includes: ["AP location survey and planning", "Cable drop to each AP location", "Ceiling or wall mount installation", "Cable testing to AP", "Coordination with IT team for configuration"],
    ideal: "Offices, retail spaces, warehouses, schools, and any commercial space needing strong wireless coverage.",
    benefits: ["Complete wireless coverage", "Reduced dead zones", "Clean ceiling-mount installations", "Scalable AP deployment"],
    caseStudy: {
      title: "Warehouse Wi-Fi Coverage — Sioux City, IA",
      summary: "A logistics warehouse had persistent dead zones affecting handheld scanners and tablets. We surveyed the facility, ran CAT6 to 14 ceiling AP locations across 80,000 sq ft, and coordinated with their Cisco Meraki provider for full deployment. Wireless issues were eliminated immediately after go-live.",
      result: "14 APs | 80,000 sq ft covered | Zero dead zones",
    },
    gallery: [
      "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    ],
  },
  {
    slug: "camera-cctv-prewire",
    icon: Camera,
    title: "Camera / CCTV Prewire",
    tagline: "Professional security camera prewire — so your integrator can hit the ground running.",
    desc: "IP and analog camera prewire installations for security surveillance systems. We run and terminate the cabling so your security integrator can install cameras quickly.",
    longDesc: "Security camera systems are only as reliable as the cabling behind them. We handle the low-voltage infrastructure side — running CAT6 for IP cameras or coax for analog systems to each planned camera location, testing all connections, and coordinating with your security vendor for a smooth install day. Our clean, hidden cable runs ensure a professional result that's easy to maintain.",
    includes: ["Camera location cable runs", "CAT6 drops for IP cameras", "Coax runs for analog systems", "Cable testing to each camera point", "Coordination with security vendors"],
    ideal: "Commercial buildings, retail stores, warehouses, parking lots, and any facility needing surveillance coverage.",
    benefits: ["Clean, hidden cable runs", "Ready for camera install", "Professional-grade cabling", "Support for IP and analog systems"],
    caseStudy: {
      title: "Retail Chain Expansion — Multiple Iowa Locations",
      summary: "A regional retail chain needed camera prewire across three new store locations simultaneously. We deployed two crews and completed all three sites within five days — running CAT6 to 28 IP camera locations per store, testing every drop, and leaving each site camera-ready for the security integrator.",
      result: "3 sites | 84 drops total | Camera-ready in 5 days",
    },
    gallery: [
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80",
    ],
  },
  {
    slug: "data-center-cabling",
    icon: DatabaseZap,
    title: "Data Center Cabling — Iowa",
    tagline: "Structured cabling and fiber infrastructure for Iowa data centers, server rooms, and colocation facilities.",
    desc: "Professional data center cabling services for Iowa businesses — including high-density copper and fiber installations, cable management, hot/cold aisle organization, and structured patching for server rooms, colocation spaces, and on-premise data facilities.",
    longDesc: "Iowa's growing data center and colocation market demands precision cabling infrastructure that supports high-density deployments, 10/25/100GbE switching fabrics, and reliable uptime. Iowa Structure Cabling Solution provides end-to-end data center cabling services — from initial pathway planning and overhead tray installation to structured fiber breakouts, copper patch fields, and complete cable management. We work in live data center environments with minimal disruption and full documentation on every project.",
    includes: [
      "Overhead and underfloor cable tray installation",
      "High-density CAT6A copper structured patching",
      "Single-mode and OM4 multimode fiber runs",
      "MTP/MPO and LC fiber breakout assemblies",
      "Top-of-rack (TOR) switch cabling",
      "Hot/cold aisle cable management and dressing",
      "Cable testing, certification, and OTDR documentation",
      "Labeling and as-built documentation",
    ],
    ideal: "Server rooms, colocation suites, on-premise data facilities, and any Iowa business running high-density network infrastructure.",
    benefits: [
      "Supports 10/25/100GbE switching fabrics",
      "Clean hot/cold aisle airflow management",
      "Scalable structured patching for rapid changes",
      "OTDR-certified fiber with full documentation",
      "Experienced in live data center environments",
    ],
    caseStudy: {
      title: "Server Room Infrastructure Build — Des Moines, IA",
      summary: "A financial services firm built out a new on-premise server room requiring 200 CAT6A copper drops across 8 patch panels, dual fiber paths between core and edge switches, and complete overhead cable tray installation. We completed the full infrastructure build in four days — delivering organized, labeled, and certified cabling ready for their equipment deployment.",
      result: "200 copper drops | Dual fiber paths | 4-day buildout",
    },
    gallery: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80",
    ],
  },
  {
    slug: "low-voltage-mac",
    icon: ArrowRightLeft,
    title: "Low-Voltage MAC Work",
    tagline: "Fast, clean moves, adds, and changes with minimal disruption to your operations.",
    desc: "Moves, adds, and changes for existing structured cabling systems. Whether you're rearranging desks, adding workstations, or relocating departments — we handle the cabling.",
    longDesc: "Business needs change constantly — and your network cabling needs to keep up. Our MAC (Moves, Adds, and Changes) service handles everything from adding a single drop to a new desk to rerouting cabling for an entire department move. We work quickly, keep disruption to a minimum, and update your cable documentation so your records stay accurate.",
    includes: ["New drop additions", "Existing drop relocation", "Patch panel port additions", "Cable rerouting and management", "Testing and re-labeling"],
    ideal: "Office moves, desk rearrangements, department expansions, and ongoing facility changes.",
    benefits: ["Minimal disruption", "Quick turnaround", "Updated documentation", "Maintained network integrity"],
    caseStudy: {
      title: "Department Relocation — Waterloo, IA",
      summary: "A healthcare company relocated an entire 40-person department to a different floor. We added 45 new drops, relocated 20 existing patch panel connections, updated all labeling, and had the new area fully operational the same day — allowing the team to move in without missing a beat.",
      result: "45 new drops | Same-day completion | Full documentation update",
    },
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=600&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    ],
  },
];