export const JOBS = [
  {
    id: "cable-technician",
    title: "Cable Technician",
    type: "Full-Time",
    level: "Entry / Mid",
    location: "Des Moines, IA",
    summary: "Install, terminate, and test structured cabling systems in commercial environments. Work alongside experienced technicians on active job sites.",
    responsibilities: [
      "Run CAT6/CAT6A cable through walls, ceilings, and conduit",
      "Terminate keystone jacks, patch panels, and wall plates",
      "Test and certify cable drops using Fluke test equipment",
      "Label and document all work per project specifications",
      "Maintain clean and organized work areas on job sites",
    ],
    requirements: [
      "1+ year of low-voltage or structured cabling experience preferred",
      "Ability to work in ceilings, attics, and tight spaces",
      "Valid driver's license and reliable transportation",
      "Willingness to travel to job sites across Iowa",
      "BICSI or industry certifications a plus",
    ],
    pay: "$18 – $28/hr depending on experience",
  },
  {
    id: "lead-technician",
    title: "Lead Cable Technician",
    type: "Full-Time",
    level: "Senior",
    location: "Des Moines, IA",
    summary: "Lead small crews on commercial cabling projects. Manage daily site operations, coordinate with GCs, and ensure quality standards are met.",
    responsibilities: [
      "Supervise and mentor 2–4 technicians on job sites",
      "Interpret blueprints and cabling schematics",
      "Ensure all work meets TIA/EIA standards",
      "Coordinate with general contractors and other trades",
      "Complete job site documentation and daily reports",
    ],
    requirements: [
      "3+ years of structured cabling experience",
      "Previous crew lead or foreman experience preferred",
      "BICSI Installer 1 or 2 certification a strong plus",
      "Strong communication and organizational skills",
      "Valid driver's license; clean driving record",
    ],
    pay: "$28 – $38/hr depending on experience",
  },
  {
    id: "fiber-optic-technician",
    title: "Fiber Optic Technician",
    type: "Full-Time",
    level: "Mid / Senior",
    location: "Des Moines, IA",
    summary: "Install and terminate single-mode and multi-mode fiber optic cabling for commercial clients. Perform fusion splicing and OTDR testing.",
    responsibilities: [
      "Install fiber optic cable in conduit, cable tray, and overhead pathways",
      "Perform fusion splicing and mechanical terminations",
      "Conduct OTDR testing and document results",
      "Mount splice trays, enclosures, and fiber patch panels",
      "Troubleshoot fiber issues and perform repairs",
    ],
    requirements: [
      "2+ years of fiber optic installation experience",
      "Hands-on fusion splicing experience required",
      "Familiarity with OTDR testing and interpretation",
      "Experience with both SM and MM fiber",
      "FOA or BICSI certification preferred",
    ],
    pay: "$26 – $40/hr depending on experience",
  },
  {
    id: "project-manager",
    title: "Project Manager",
    type: "Full-Time",
    level: "Mid / Senior",
    location: "Des Moines, IA",
    summary: "Manage the full lifecycle of commercial cabling projects — from pre-construction planning and scheduling to final closeout and client communication.",
    responsibilities: [
      "Manage multiple concurrent commercial cabling projects",
      "Build and maintain project schedules and budgets",
      "Serve as primary point of contact for clients and GCs",
      "Coordinate crews, materials, and subcontractors",
      "Review drawings, RFIs, and submittals",
      "Ensure projects are delivered on time, on budget, and to spec",
    ],
    requirements: [
      "3+ years of project management experience in low-voltage, electrical, or construction",
      "Strong understanding of structured cabling systems",
      "Proficiency with project management software",
      "Excellent written and verbal communication skills",
      "PMP or industry certification a plus",
    ],
    pay: "$65,000 – $90,000/yr depending on experience",
  },
  {
    id: "estimator",
    title: "Estimator / Pre-Construction",
    type: "Full-Time",
    level: "Mid",
    location: "Des Moines, IA (Hybrid)",
    summary: "Prepare detailed bids and estimates for commercial low-voltage projects. Review drawings, develop scope of work, and support the sales process.",
    responsibilities: [
      "Perform material and labor takeoffs from project drawings",
      "Prepare accurate bids and proposals for GCs and direct clients",
      "Develop scope of work documents and bid packages",
      "Coordinate with project managers during pre-construction",
      "Track bid outcomes and maintain estimating database",
    ],
    requirements: [
      "2+ years of low-voltage or electrical estimating experience",
      "Ability to read and interpret construction drawings",
      "Experience with estimating software preferred",
      "Strong attention to detail and analytical skills",
      "Understanding of structured cabling materials and labor costs",
    ],
    pay: "$55,000 – $75,000/yr depending on experience",
  },
  {
    id: "apprentice-technician",
    title: "Apprentice Cable Technician",
    type: "Full-Time",
    level: "Entry Level",
    location: "Des Moines, IA",
    summary: "No experience required — learn the trade from the ground up alongside our experienced crew. This is a hands-on training position with a clear path to advancement.",
    responsibilities: [
      "Assist senior technicians with cable pulls and installations",
      "Learn proper termination and testing techniques",
      "Keep job sites clean and materials organized",
      "Follow all safety guidelines and company procedures",
      "Complete assigned training modules and certifications",
    ],
    requirements: [
      "No prior experience necessary — we will train the right person",
      "Strong work ethic and eagerness to learn",
      "Ability to perform physical work in various environments",
      "Valid driver's license",
      "Reliable and punctual",
    ],
    pay: "$16 – $20/hr starting, with regular increases",
  },
  {
    id: "warehouse-coordinator",
    title: "Warehouse & Materials Coordinator",
    type: "Full-Time",
    level: "Entry / Mid",
    location: "Des Moines, IA",
    summary: "Manage inventory, stage materials for job sites, and support field crews with logistics. Keep the warehouse organized and stocked.",
    responsibilities: [
      "Receive, organize, and track incoming materials and equipment",
      "Stage materials for upcoming projects and field crews",
      "Coordinate deliveries and pickups with vendors",
      "Maintain accurate inventory records",
      "Support project managers with material procurement",
    ],
    requirements: [
      "1+ year of warehouse, inventory, or logistics experience preferred",
      "Organized and detail-oriented",
      "Forklift certification a plus",
      "Basic computer skills for inventory tracking",
      "Ability to lift 50+ lbs regularly",
    ],
    pay: "$18 – $25/hr depending on experience",
  },
  {
    id: "field-supervisor",
    title: "Field Supervisor / Foreman",
    type: "Full-Time",
    level: "Senior",
    location: "Statewide Iowa",
    summary: "Oversee multiple job sites and crews across Iowa. Act as the on-site authority for quality control, safety, and client relations.",
    responsibilities: [
      "Supervise field technicians across multiple simultaneous projects",
      "Ensure work quality meets company and industry standards",
      "Conduct safety briefings and enforce jobsite protocols",
      "Resolve on-site issues and coordinate with project managers",
      "Review and approve daily field reports and timesheets",
    ],
    requirements: [
      "5+ years of structured cabling or low-voltage field experience",
      "2+ years in a supervisory or foreman role",
      "Ability to manage multiple crews and projects simultaneously",
      "Strong leadership and problem-solving skills",
      "OSHA 10 or 30 certification preferred",
    ],
    pay: "$38 – $52/hr depending on experience",
  },
];